---
title: "Resumen gr치fico de datos en R"
author: "Fernando Salcedo, ALZAK Foundation"
date: 2023-08-19
format: 
  revealjs :
    logo: "src/alzak_foundation.png"
    footer: "Copyright (c) 2023, Fernando Salcedo"
    scrollable: true
    margin: 0
execute:
  echo: true
enbeded: true
---

## Preparativos 游닇

- Cree una carpeta con la estructura vista en el curso.
- Ver **Crear un projecto de ciencia de datos con Rstudio** en `01_instalacion_R_Rstudio.html` para recordar lo visto.
- Enviar la carpeta comprimida en formato `.zip` con la soluci칩n al correo del tutor.

## Prueba lo que has aprendido 1 游

- Cree un script con el nombre `01_tidy_poblacion.R` y desarrolle.
- Usando los reportes de proyecci칩n de poblaci칩n del DANE entre 1985 a 2035 que est치 en formato `.xlsx` realice :
- Importa las distintas bases de datos de poblaci칩n a `R`.
- Limpia los nombres usando `janitor`.
- Para cada base, trasponga los datos en formato `tidy` a lo largo donde est칠n las variables : `codigo_dpto, nombre_dpto, codigo_muncipio, nombre_municipio, a침o, edad, sexo, poblacion`.
- Pegue verticalmente todas las bases de los distintos a침os usando `bind_rows()`.
- Exporta a un archivo plano delimitado por comas el resultado anterior. Use el nombre `proyeccion_poblacion_1985_2035.csv`.
- Guardar la base en formato `rds`. Use el nombre `proyeccion_poblacion_1985_2035.rds`.

## Prueba lo que has aprendido 2 游

- Cree un script con el nombre `02_analisis.R` y desarrolle.
- Cargue los datos `proyeccion_poblacion_1985_2035.rds` usando `readRDS()`.
- Calcule el aumento de la poblaci칩n total y el incremento porcentual de la poblaci칩n total entre 2018 y 2035.
- Repita los c치lculos del aumento e incremento de la poblaci칩n entre 2018 y 2035 para cada departamento.
- Realice un gr치fico de l칤neas de la poblaci칩n colombiana entre 1985 y 2035 usando `ggplot2`.
- Repita el gr치fico anterior pero discriminado por departamento usando `ggplot2`.

## Ayuda 游뚿游뚿游뚿

- Todas las presentaciones y scripts desarrollados en el curso est치n disponibles en el repositorio.
- Puedes contactar al tutor del curso si tiene dudas.


